format = """
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#33658A)\
$username\
[ ](fg:#33658A)\
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#616D88"

[username]
show_always = true
format = '[  ](bg:#33658A)'

[c]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
format = '[ $symbol ($version) ]($style)'

