#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding			 25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 4
bspc config focus_follows_pointer true
bspc config active_border_color "#344C73"
bspc config normal_border_color "#2F3846"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rile -a override-redirect = true
feh --bg-scale /home/maz/Downloads/212811.jpg
polybar main &
picom &
lxpolkit &
setxkbmap -option grp:alt_shift_toggle us,ar &
xsetroot -cursor_name left_ptr &
